### ISSUE TITLE
Maybe use https://allcontributors.org/

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-playwright#5]
For managing contributor things?

**Comment by aaltat** [comment]
Never used, would need read what it offers. It's partially related to release too. [Rellu](https://github.com/robotframework/rellu) does similar thing by parsing issues and adding contributors to the release notes.

**Comment by mkorpela** [comment]
Now using this https://contributors-img.web.app/

**Comment by mkorpela** [comment]
@all-contributors please add mkorpela for development

**Comment by mkorpela** [comment]
@all-contributors please add mkorpela for code

**Comment by mkorpela** [comment]
@all-contributors please add aaltat for code

**Comment by mkorpela** [comment]
This is awesome!
